### ISSUE TITLE
Declare a license

### ISSUE THREAD

**Issue by Freso** [agrausem/beets-artistcountry#2]
Hello,

Any chance you could declare a license for this plugin? (Upstream beets is using [an MIT license](https://github.com/beetbox/beets/blob/master/LICENSE), so using that would make it 1:1 compatible for inclusion in upstream.)

**Comment by Freso** [comment]
I've filed an issue with beets to copy this functionality into upstream: https://github.com/beetbox/beets/issues/2338 – if this plugin was(/is) MIT licensed, code could(/can) be copied over directly.

**Comment by agrausem** [comment]
Hello,

Sorry for the delay. I just declared an MIT license for the plugin.
Many thanks !
